from card_actions.card_base import *
card_lookup = {
   # ArtifactCard
"Arcane Signet": ArtifactCard("arcane_signet"),
"Colfenors Urn": ArtifactCard("colfenors_urn"),
"Cursed Mirror": ArtifactCard("cursed_mirror"),
"Heralds Horn": ArtifactCard("heralds_horn"),
"Maskwood Nexus": ArtifactCard("maskwood_nexus"),
"Oketras Monument": ArtifactCard("oketras_monument"),
"Orzhov Signet": ArtifactCard("orzhov_signet"),
"Selesnya Signet": ArtifactCard("selesnya_signet"),
"Sol Ring": ArtifactCard("sol_ring"),
"Staff Of Compleation": ArtifactCard("staff_of_compleation"),
"Vanquishers Banner": ArtifactCard("vanquishers_banner"),

# ArtifactCreatureCard
"Crashing Drawbridge": ArtifactCreatureCard("crashing_drawbridge", power=0, toughness=4),
"Wakestone Gargoyle": ArtifactCreatureCard("wakestone_gargoyle", power=3, toughness=4),

# ArtifactEquipmentCreatureCard
"Komainu Battle Armor": ArtifactEquipmentCreatureCard("komainu_battle_armor", power=2, toughness=2, reconfigure_cost=4),

# CreatureCard
"Alms Collector": CreatureCard("alms_collector", power=3, toughness=4),
"Arasta Of The Endless Web": EnchantmentCreatureCard("arasta_of_the_endless_web", power=3, toughness=5),
"Arbor Adherent": CreatureCard("arbor_adherent", power=2, toughness=4),
"Arboreal Grazer": CreatureCard("arboreal_grazer", power=0, toughness=0),
"Axebane Guardian": CreatureCard("axebane_guardian", power=0, toughness=3),
"Baldin Century Herdmaster": CreatureCard("baldin_century_herdmaster", power=0, toughness=7),
"Betor Ancestors Voice": CreatureCard("betor_ancestors_voice", power=3, toughness=5),
"Blight Pile": CreatureCard("blight_pile", power=3, toughness=3),
"Bloodline Pretender": CreatureCard("bloodline_pretender", power=2, toughness=2),
"Brimaz King Of Oreskos": CreatureCard("brimaz_king_of_oreskos", power=3, toughness=4),
"Canopy Gargantuan": CreatureCard("canopy_gargantuan", power=7, toughness=7),
"Carven Caryatid": CreatureCard("carven_caryatid", power=2, toughness=5),
"Dragonlord Dromoka": CreatureCard("dragonlord_dromoka", power=5, toughness=7),
"Faeburrow Elder": CreatureCard("faeburrow_elder", power=0, toughness=0),
"Feline Sovereign": CreatureCard("feline_sovereign", power=2, toughness=3),
"Felothar The Steadfast": CreatureCard("felothar_the_steadfast", power=0, toughness=5),
"Fleetfoot Panther": CreatureCard("fleetfoot_panther", power=3, toughness=4),
"Fortified Village": LandCard("fortified_village"),
"Greater Tanuki": EnchantmentCreatureCard("greater_tanuki", power=6, toughness=5),
"Highcliff Felidar": CreatureCard("highcliff_felidar", power=5, toughness=5),
"Hornet Nest": CreatureCard("hornet_nest", power=0, toughness=2),
"Hungry Lynx": CreatureCard("hungry_lynx", power=2, toughness=2),
"Ikra Shidiqi The Usurper": CreatureCard("ikra_shidiqi_the_usurper", power=3, toughness=7),
"Indomitable Ancients": CreatureCard("indomitable_ancients", power=2, toughness=10),
"Indulging Patrician": CreatureCard("indulging_patrician", power=1, toughness=4),
"Jaddi Offshoot": CreatureCard("jaddi_offshoot", power=0, toughness=3),
"Jazal Goldmane": CreatureCard("jazal_goldmane", power=4, toughness=4),
"Jetmir Nexus Of Revels": CreatureCard("jetmir_nexus_of_revels", power=5, toughness=4),
"Jinnie Fay Jetmirs Second": CreatureCard("jinnie_fay_jetmirs_second", power=3, toughness=3),
"Keeper Of Fables": CreatureCard("keeper_of_fables", power=4, toughness=5),
"King Of The Pride": CreatureCard("king_of_the_pride", power=2, toughness=1),
"Kitt Kanto Mayhem Diva": CreatureCard("kitt_kanto_mayhem_diva", power=3, toughness=3),
"Lion Sash": ArtifactEquipmentCreatureCard("lion_sash", power=1, toughness=1, reconfigure_cost=2),
"Loyal Warhound": CreatureCard("loyal_warhound", power=3, toughness=1),
"Lurking Predators": EnchantmentCard("lurking_predators"),
"Marisi Breaker Of The Coil": CreatureCard("marisi_breaker_of_the_coil", power=5, toughness=4),
"Masked Vandal": CreatureCard("masked_vandal", power=1, toughness=3),
"Nacatl Warpride": CreatureCard("nacatl_warpride", power=3, toughness=3),
"Nyx Fleece Ram": CreatureCard("nyx_fleece_ram", power=0, toughness=5),
"Oreskos Explorer": CreatureCard("oreskos_explorer", power=2, toughness=2),
"Pack Leader": CreatureCard("pack_leader", power=2, toughness=2),
"Phabine Bosss Confidant": CreatureCard("phabine_bosss_confidant", power=3, toughness=6),
"Protector Of The Wastes": CreatureCard("protector_of_the_wastes", power=5, toughness=5),
"Qasali Slingers": CreatureCard("qasali_slingers", power=3, toughness=5),
"Rampart Architect": CreatureCard("rampart_architect", power=3, toughness=4),
"Realmwalker": CreatureCard("realmwalker", power=2, toughness=3),
"Regal Caracal": CreatureCard("regal_caracal", power=3, toughness=3),
"Rhox Faithmender": CreatureCard("rhox_faithmender", power=1, toughness=5),
"Rin And Seri Inseparable": CreatureCard("rin_and_seri_inseparable", power=4, toughness=4),
"Seedborn Muse": CreatureCard("seedborn_muse", power=2, toughness=4),
"Sehts Tiger": CreatureCard("sehts_tiger", power=3, toughness=4),
"Shadrix Silverquill": CreatureCard("shadrix_silverquill", power=2, toughness=5),
"Shalai Voice Of Plenty": CreatureCard("shalai_voice_of_plenty", power=3, toughness=4),
"Sidar Kondo Of Jamuraa": CreatureCard("sidar_kondo_of_jamuraa", power=2, toughness=5),
"Skyhunter Strike Force": CreatureCard("skyhunter_strike_force", power=2, toughness=2),
"Slaughter The Strong": SorceryCard("slaughter_the_strong"),
"Stalking Leonin": CreatureCard("stalking_leonin", power=3, toughness=3),
"Sylvan Caryatid": CreatureCard("sylvan_caryatid", power=0, toughness=3),
"Taurean Mauler": CreatureCard("taurean_mauler", power=2, toughness=2),
"Temur Sabertooth": CreatureCard("temur_sabertooth", power=4, toughness=3),
"Tree Of Redemption": CreatureCard("tree_of_redemption", power=0, toughness=13),
"Walking Bulwark": CreatureCard("walking_bulwark", power=0, toughness=3),
"Wall Of Blossoms": CreatureCard("wall_of_blossoms", power=0, toughness=4),
"Wall Of Limbs": CreatureCard("wall_of_limbs", power=0, toughness=3),
"Wall Of Omens": CreatureCard("wall_of_omens", power=0, toughness=4),
"Wall Of Reverence": CreatureCard("wall_of_reverence", power=1, toughness=6),
"Wall Of Roots": CreatureCard("wall_of_roots", power=0, toughness=5),
"Weathered Sentinels": CreatureCard("weathered_sentinels", power=2, toughness=5),
"Welcoming Vampire": CreatureCard("welcoming_vampire", power=2, toughness=3),
"Whitemane Lion": CreatureCard("whitemane_lion", power=2, toughness=2),
"Wingmantle Chaplain": CreatureCard("wingmantle_chaplain", power=0, toughness=3),
"Zetalpa Primal Dawn": CreatureCard("zetalpa_primal_dawn", power=4, toughness=8),

# EnchantmentCard
"Anointed Procession": EnchantmentCard("anointed_procession"),
"Assault Formation": EnchantmentCard("assault_formation"),
"Beastmaster Ascension": EnchantmentCard("beastmaster_ascension"),
"Behind The Scenes": EnchantmentCard("behind_the_scenes"),
"Cast Out": EnchantmentCard("cast_out"),
"Clifftop Retreat": LandCard("clifftop_retreat"),
"Felidar Retreat": EnchantmentCard("felidar_retreat"),
"Impact Tremors": EnchantmentCard("impact_tremors"),
"Jaws Of Defeat": EnchantmentCard("jaws_of_defeat"),
"Tocasias Welcome": EnchantmentCard("tocasias_welcome"),

# EnchantmentCreatureCard
"Spirited Companion": EnchantmentCreatureCard("spirited_companion", power=1, toughness=1),

# EquipmentCard
"Basilisk Collar": EquipmentCard("basilisk_collar", equip_cost=1),

# InstantCard
"Anguished Unmaking": InstantCard("anguished_unmaking"),
"Crib Swap": InstantCard("crib_swap"),
"Despark": InstantCard("despark"),
"Infernal Grasp": InstantCard("infernal_grasp"),
"Path To Exile": InstantCard("path_to_exile"),
"Swords To Plowshares": InstantCard("swords_to_plowshares"),
"Tower Defense": InstantCard("tower_defense"),

# LandCard
"Access Tunnel": LandCard("access_tunnel"),
"Animal Sanctuary": LandCard("animal_sanctuary"),
"Bojuka Bog": LandCard("bojuka_bog"),
"Canopy Vista": LandCard("canopy_vista"),
"Cinder Glade": LandCard("cinder_glade"),
"Command Tower": LandCard("command_tower"),
"Deceptive Landscape": LandCard("deceptive_landscape"),
"Evolving Wilds": LandCard("evolving_wilds"),
"Exotic Orchard": LandCard("exotic_orchard"),
"Forest": LandCard("forest"),
"Game Trail": LandCard("game_trail"),
"Isolated Chapel": LandCard("isolated_chapel"),
"Jetmirs Garden": LandCard("jetmirs_garden"),
"Jungle Shrine": LandCard("jungle_shrine"),
"Krosan Verge": LandCard("krosan_verge"),
"Mountain": LandCard("mountain"),
"Overgrown Battlement": LandCard("overgrown_battlement"),
"Overgrown Farmland": LandCard("overgrown_farmland"),
"Path Of Ancestry": LandCard("path_of_ancestry"),
"Plains": LandCard("plains"),
"Radiant Grove": LandCard("radiant_grove"),
"Rootbound Crag": LandCard("rootbound_crag"),
"Sandsteppe Citadel": LandCard("sandsteppe_citade"),
"Scattered Groves": LandCard("scattered_groves"),
"Sheltered Thicket": LandCard("sheltered_thicket"),
"Sungrass Prairie": LandCard("sungrass_prairie"),
"Sunpetal Grove": LandCard("sunpetal_grove"),
"Swamp": LandCard("swamp"),
"Temple Of Malady": LandCard("temple_of_malady"),
"Temple Of Plenty": LandCard("temple_of_plenty"),
"Temple Of Silence": LandCard("temple_of_silence"),
"Twilight Mire": LandCard("twilight_mire"),
"Woodland Cemetery": LandCard("woodland_cemetery"),

# SorceryCard
"Cultivate": SorceryCard("cultivate"),
"Expel The Interlopers": SorceryCard("expel_the_interlopers"),
"Farseek": SorceryCard("farseek"),
"Feed The Swarm": SorceryCard("feed_the_swarm"),
"Natures Lore": SorceryCard("natures_lore"),
"Return Of The Wildspeaker": SorceryCard("return_of_the_wildspeaker"),
"Reunion Of The House": SorceryCard("reunion_of_the_house"),
"Showdown Of The Skalds": SorceryCard("showdown_of_the_skalds"),
"Three Visits": SorceryCard("three_visits"),
"Tip The Scales": SorceryCard("tip_the_scales"),
"Warp World": SorceryCard("warp_world"),
"White Suns Zenith": SorceryCard("white_suns_zenith"),
"Will Of The Abzan": SorceryCard("will_of_the_abzan"),

# SplitCard
"Duskdawn": SplitCard(
    name="Dusk // Dawn",
    left_name="Dusk",
    right_name="Dawn",
    left_type="Sorcery",
    right_type="Sorcery"
),

}